"""This modules provides information on the Kangxi radicals."""

from typing import NamedTuple


class Radical(NamedTuple):
    """Information on a single radical which may have multiple variants and meanings."""

    radical: str
    variants: list[str]
    meanings: list[str]

    def __str__(self):
        variants = f"({', '.join(self.variants)}) " if self.variants else ""
        return f"{self.radical} {variants}({', '.join(self.meanings)})"


"""
A list of Kangxi radicals where the index in the list corresponds to the official
radical number.
"""
KANGXI_RADICALS = [
    Radical("一", [], ["one"]),
    Radical("丨", [], ["line"]),
    Radical("丶", [], ["dot"]),
    Radical("丿", ["乀", "⺄"], ["slash"]),
    Radical("乙", ["乚", "乛"], ["second"]),
    Radical("亅", [], ["hook"]),
    Radical("二", [], ["two"]),
    Radical("亠", [], ["lid"]),
    Radical("人", ["亻"], ["man"]),
    Radical("儿", [], ["son", "legs"]),
    Radical("入", [], ["enter"]),
    Radical("八", ["丷"], ["eight"]),
    Radical("冂", [], ["wide"]),
    Radical("冖", [], ["cloth cover"]),
    Radical("冫", [], ["ice"]),
    Radical("几", [], ["table"]),
    Radical("凵", [], ["receptacle"]),
    Radical("刀", ["刂", "⺈"], ["knife"]),
    Radical("力", [], ["power"]),
    Radical("勹", [], ["wrap"]),
    Radical("匕", [], ["spoon"]),
    Radical("匚", [], ["box"]),
    Radical("匸", [], ["hiding enclosure"]),
    Radical("十", [], ["ten"]),
    Radical("卜", [], ["divination"]),
    Radical("卩", ["㔾"], ["seal (device)"]),
    Radical("厂", [], ["cliff"]),
    Radical("厶", [], ["private"]),
    Radical("又", [], ["again"]),
    Radical("口", [], ["mouth"]),
    Radical("囗", [], ["enclosure"]),
    Radical("土", [], ["earth"]),
    Radical("士", [], ["scholar"]),
    Radical("夂", [], ["go"]),
    Radical("夊", [], ["go slowly"]),
    Radical("夕", [], ["evening"]),
    Radical("大", [], ["big"]),
    Radical("女", [], ["woman"]),
    Radical("子", [], ["child"]),
    Radical("宀", [], ["roof"]),
    Radical("寸", [], ["inch"]),
    Radical("小", ["⺌", "⺍"], ["small"]),
    Radical("尢", ["尣"], ["lame"]),
    Radical("尸", [], ["corpse"]),
    Radical("屮", [], ["sprout"]),
    Radical("山", [], ["mountain"]),
    Radical("巛", ["川"], ["river"]),
    Radical("工", [], ["work"]),
    Radical("己", [], ["oneself"]),
    Radical("巾", [], ["turban"]),
    Radical("干", [], ["dry"]),
    Radical("幺", ["么"], ["short thread"]),
    Radical("广", [], ["dotted cliff"]),
    Radical("廴", [], ["long stride"]),
    Radical("廾", [], ["arch"]),
    Radical("弋", [], ["shoot"]),
    Radical("弓", [], ["bow"]),
    Radical("彐", ["彑"], ["snout"]),
    Radical("彡", [], ["bristle"]),
    Radical("彳", [], ["step"]),
    Radical("心", ["忄", "⺗"], ["heart"]),
    Radical("戈", [], ["halberd"]),
    Radical("戶", ["户", "戸"], ["door"]),
    Radical("手", ["扌", "龵"], ["hand"]),
    Radical("支", [], ["branch"]),
    Radical("攴", ["攵"], ["rap", "tap"]),
    Radical("文", [], ["script"]),
    Radical("斗", [], ["dipper"]),
    Radical("斤", [], ["axe"]),
    Radical("方", [], ["square"]),
    Radical("无", ["旡"], ["not"]),
    Radical("日", [], ["sun"]),
    Radical("曰", [], ["say"]),
    Radical("月", [], ["moon"]),
    Radical("木", [], ["tree"]),
    Radical("欠", [], ["lack"]),
    Radical("止", [], ["stop"]),
    Radical("歹", ["歺"], ["death"]),
    Radical("殳", [], ["weapon"]),
    Radical("毋", ["母"], ["do not"]),
    Radical("比", [], ["compare"]),
    Radical("毛", [], ["fur"]),
    Radical("氏", [], ["clan"]),
    Radical("气", [], ["steam"]),
    Radical("水", ["氵", "氺"], ["water"]),
    Radical("火", ["灬"], ["fire"]),
    Radical("爪", ["爫"], ["claw"]),
    Radical("父", [], ["father"]),
    Radical("爻", [], ["trigrams"]),
    Radical("爿", ["丬"], ["split wood"]),
    Radical("片", [], ["slice"]),
    Radical("牙", [], ["fang"]),
    Radical("牛", ["牜", "⺧"], ["cow"]),
    Radical("犬", ["犭"], ["dog"]),
    Radical("玄", [], ["profound"]),
    Radical("玉", ["王", "玊"], ["jade"]),
    Radical("瓜", [], ["melon"]),
    Radical("瓦", [], ["tile"]),
    Radical("甘", [], ["sweet"]),
    Radical("生", [], ["life"]),
    Radical("用", [], ["use"]),
    Radical("田", [], ["field"]),
    Radical("疋", ["⺪"], ["bolt of cloth"]),
    Radical("疒", [], ["sickness"]),
    Radical("癶", [], ["footsteps"]),
    Radical("白", [], ["white"]),
    Radical("皮", [], ["skin"]),
    Radical("皿", [], ["dish"]),
    Radical("目", ["⺫"], ["eye"]),
    Radical("矛", [], ["spear"]),
    Radical("矢", [], ["arrow"]),
    Radical("石", [], ["stone"]),
    Radical("示", ["礻"], ["spirit"]),
    Radical("禸", [], ["track"]),
    Radical("禾", [], ["grain"]),
    Radical("穴", [], ["cave"]),
    Radical("立", [], ["stand"]),
    Radical("竹", ["⺮"], ["bamboo"]),
    Radical("米", [], ["rice"]),
    Radical("糸", ["糹"], ["silk"]),
    Radical("缶", [], ["jar"]),
    Radical("网", ["⺲", "罓", "⺳"], ["net"]),
    Radical("羊", ["⺶", "⺷"], ["sheep"]),
    Radical("羽", [], ["feather"]),
    Radical("老", ["耂"], ["old"]),
    Radical("而", [], ["and"]),
    Radical("耒", [], ["plow"]),
    Radical("耳", [], ["ear"]),
    Radical("聿", ["⺺", "⺻"], ["brush"]),
    Radical("肉", ["⺼"], ["meat"]),
    Radical("臣", [], ["minister"]),
    Radical("自", [], ["self"]),
    Radical("至", [], ["arrive"]),
    Radical("臼", [], ["mortar"]),
    Radical("舌", [], ["tongue"]),
    Radical("舛", [], ["oppose"]),
    Radical("舟", [], ["boat"]),
    Radical("艮", [], ["stopping"]),
    Radical("色", [], ["color"]),
    Radical("艸", ["⺿"], ["grass"]),
    Radical("虍", [], ["tiger"]),
    Radical("虫", [], ["insect"]),
    Radical("血", [], ["blood"]),
    Radical("行", [], ["walk enclosure"]),
    Radical("衣", ["⻂"], ["clothes"]),
    Radical("襾", ["西", "覀"], ["cover"]),
    Radical("見", [], ["see"]),
    Radical("角", ["⻇"], ["horn (of an animal)"]),
    Radical("言", ["訁"], ["speech"]),
    Radical("谷", [], ["valley"]),
    Radical("豆", [], ["bean"]),
    Radical("豕", [], ["pig"]),
    Radical("豸", [], ["badger"]),
    Radical("貝", [], ["shell"]),
    Radical("赤", [], ["red"]),
    Radical("走", [], ["run"]),
    Radical("足", ["⻊"], ["foot"]),
    Radical("身", [], ["body"]),
    Radical("車", [], ["cart"]),
    Radical("辛", [], ["bitter"]),
    Radical("辰", [], ["morning"]),
    Radical("辵", ["⻌", "⻍", "⻎"], ["walk"]),
    Radical("邑", ["⻏"], ["city"]),
    Radical("酉", [], ["wine"]),
    Radical("釆", [], ["distinguish"]),
    Radical("里", [], ["village"]),
    Radical("金", ["釒"], ["gold"]),
    Radical("長", ["镸"], ["long"]),
    Radical("門", [], ["gate"]),
    Radical("阜", ["⻖"], ["mound"]),
    Radical("隶", [], ["slave"]),
    Radical("隹", [], ["short-tailed bird"]),
    Radical("雨", [], ["rain"]),
    Radical("靑", ["青"], ["blue"]),
    Radical("非", [], ["wrong"]),
    Radical("面", ["靣"], ["face"]),
    Radical("革", [], ["leather"]),
    Radical("韋", [], ["tanned leather"]),
    Radical("韭", [], ["leek"]),
    Radical("音", [], ["sound"]),
    Radical("頁", [], ["leaf"]),
    Radical("風", [], ["wind"]),
    Radical("飛", [], ["fly"]),
    Radical("食", ["飠"], ["eat"]),
    Radical("首", [], ["head"]),
    Radical("香", [], ["fragrant"]),
    Radical("馬", [], ["horse"]),
    Radical("骨", [], ["bone"]),
    Radical("高", ["髙"], ["tall"]),
    Radical("髟", [], ["hair"]),
    Radical("鬥", [], ["fight"]),
    Radical("鬯", [], ["sacrificial wine"]),
    Radical("鬲", [], ["cauldron"]),
    Radical("鬼", [], ["ghost"]),
    Radical("魚", [], ["fish"]),
    Radical("鳥", [], ["bird"]),
    Radical("鹵", [], ["salt"]),
    Radical("鹿", [], ["deer"]),
    Radical("麥", [], ["wheat"]),
    Radical("麻", [], ["hemp"]),
    Radical("黃", [], ["yellow"]),
    Radical("黍", [], ["millet"]),
    Radical("黑", [], ["black"]),
    Radical("黹", [], ["embroidery"]),
    Radical("黽", [], ["frog"]),
    Radical("鼎", [], ["tripod"]),
    Radical("鼓", [], ["drum"]),
    Radical("鼠", [], ["rat"]),
    Radical("鼻", [], ["nose"]),
    Radical("齊", ["斉"], ["even"]),
    Radical("齒", [], ["tooth"]),
    Radical("龍", [], ["dragon"]),
    Radical("龜", [], ["turtle"]),
    Radical("龠", [], ["flute"]),
]
